# This workflow will install Python dependencies and run tests with a specific Python version
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
    - name: Install fake precice
      run:  |
          mkdir -p precice
          echo "from setuptools import setup" >> precice/setup.py
          echo "setup(name='pyprecice', version='2.5.0')" >> precice/setup.py
          python3 -m pip install ./precice/
    - name: Test with pytest
      run: |
        pip install pytest pytest-mock
        pytest
